//
//  Gat+Text.swift
//  gat
//
//  Created by HungTran on 6/12/17.
//  Copyright © 2017 GaTBook. All rights reserved.
//

import Foundation

extension Gat {
    /**Text: Lưu các thông báo sẽ xuất hiện trong app
     Vì tên biến kiểu Text này có thể sẽ bị dài nên
     buộc được viết theo phong cách snake_case để cho
     dễ đọc trong code.*/
    
    struct Text {
        static let ADMIN_NAME = "GaT"
        
        static let FACEBOOK_TITLE = "Facebook"
        static let TWITTER_TITLE = "Twitter"
        static let GOOGLE_TITLE = "Google"
        
        struct CommonError {}
        
        struct Date {}
        
        struct TabBar {}
        
        struct Home {}
        
        struct Category {}
        
        struct NearByUser {}
        
        struct Search {}
        
        struct BookDetail {}
        
        struct AddBook {}
        
        struct ListSharingBook {}
        
        struct SortByListSharingBook {}
        
        struct Comment {}
        
        struct Bookstop {}
        
        struct Message {}
        
        struct Notification {}
        
        struct RequestDetailBorrower {}
        
        struct UserProfile {}
        
        struct VistorUserProfile {}
        
        struct StartApp {}
        
        struct Login {}
        
        struct Register {}
        
        struct Map {}
        
        struct FavouriteCategory {}
        
        struct ForgotPassword {}
        
        struct ResetPasswordForSocial {}
        
        struct ConfirmPassword {}
        
        struct ResetPassword {}
        
        struct Barcode {}
        
        struct EditUser {}
        
        struct Setting {}
        
        struct AddEmailAndPassword {}
        
        struct SocialNetwork {}
        
        struct ChangePassword {}
        
        struct OwnerRequestDetail {}
        
        struct BorrowerRequestDetail {}
        
        struct TopBorrowBook {}
        
        struct BookstopExplore {}
        
        struct ReviewExplore {}
        
        struct RequestBorrowerBookstop {}
        
        struct RequestBookstop {}
        
        struct BookstopOrganization {}
        
        struct BookstopOrganizaionShelve {}
        
        struct JoinBookstop {}
        
        static let FREE_PRICE_ORDER_TITLE = "FREE_PRICE_ORDER_TITLE".localized()
        
        struct Language {}
        
        struct Filterable {}
        
        static let SEARCH_PLACEHOLDER = "SEARCH_PLACEHOLDER" //nhap tu khoa
        
        static let OTHER = "OTHER"
        
        struct AddNewBook { }
        
        struct BookSuggest { }
        
        static let FOLLOWERS_TITLE = "FOLLOWERS_TITLE"
        
        static let FOLLOWINGS_TITLE = "FOLLOWINGS_TITLE"
        
        static let FOLLOW_TITLE = "FOLLOW_TITLE"
        
        static let UNFOLLOW_TITLE = "UNFOLLOW_TITLE"
        
        static let FOLLOWING_TITLE = "FOLLOWING_TITLE"
        
        static let LESS_TITLE = "LESS_TITLE"
        
        static let UNFOLLOW_MESSAGE = "UNFOLLOW_MESSAGE"
        
        static let UNFOLLOW_ALERT_TITLE = "UNFOLLOW_ALERT_TITLE"
        
        struct Bookmark { }
        
        struct BookUpdate {}
        
        struct JoinBarcode {}
        
        struct Gatup {}
        
        struct Guideline {}
    }
}

extension Gat.Text.Date {
    static let YEARS = "YEARS"
    static let ONE_MONTH = "ONE_MONTH"
    static let MONTHS = "MONTHS"
    static let ONE_WEEK = "ONE_WEEK"
    static let WEEKS = "WEEKS"
    static let ONE_DAY = "ONE_DAY"
    static let DAYS = "DAYS"
    static let HOURS = "HOURS"
    static let MINUTES = "MINUTES"
    static let SECONDS = "SECONDS"
}

extension Gat.Text.CommonError {
    static let ERROR_GPS_MESSAGE = "ERROR_GPS_MESSAGE"
    static let ERROR_CONNECT_INTERNET_MESSAGE = "ERROR_CONNECT_INTERNET_MESSAGE"
    static let ERROR_CONNECT_INTERNET_TITLE = "ERROR_CONNECT_INTERNET_TITLE"
    static let ERROR_LOGIN_TITLE = "ERROR_LOGIN_TITLE"
    static let SKIP_ALERT_TITLE = "SKIP_ALERT_TITLE"
    static let LOGIN_ALERT_TITLE = "LOGIN_ALERT_TITLE"
    static let LOGIN_ALERT_MESSAGE = "LOGIN_ALERT_MESSAGE"
    static let ERROR_CAMERA_TITLE = "ERROR_CAMERA_TITLE"
    static let CAMERA_ALERT_MESSAGE = "CAMERA_ALERT_MESSAGE"
    static let SETTING_ALERT_TITLE = "SETTING_ALERT_TITLE"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE"
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE"
    static let ERROR_LOCATION_TITLE = "ERROR_LOCATION_TITLE"
    static let CANCEL_NOTIFICATION_ALERT_TITLE = "CANCEL_NOTIFICATION_ALERT_TITLE"
    static let YES_ALERT_TITLE = "YES_ALERT_TITLE"
    static let NO_ALERT_TITLE = "NO_ALERT_TITLE"
    static let CANCEL_CHANGE_MESSAGE = "CANCEL_CHANGE_MESSAGE"
    static let LOST_BOOK_ALERT_TITLE = "LOST_BOOK_ALERT_TITLE"
    static let LOST_BOOK_MESSAGE = "LOST_BOOK_MESSAGE"
    static let LOST_ALERT_TITLE = "LOST_ALERT_TITLE"
    static let CANCEL_REQUEST_MESSAGE = "CANCEL_REQUEST_MESSAGE"
    static let CANCEL_REQUEST_ERROR_TITLE = "CANCEL_REQUEST_ERROR_TITLE"
    static let REJECT_ERROR_TITLE = "REJECT_ERROR_TITLE"
    static let REJECT_MESSAGE = "REJECT_MESSAGE"
    static let ERROR_EMAIL_EXISTED_TITLE = "ERROR_EMAIL_EXISTED_TITLE"
    static let EMAIL_EXISTED_MESSAGE = "EMAIL_EXISTED_MESSAGE"
    static let SOCIAL_LOGIN_NOTIFICATION = "SOCIAL_LOGIN_NOTIFICATION"
    static let SOCIAL_LOGIN_MESSAGE = "SOCIAL_LOGIN_MESSAGE"
    static let ERROR_SOCIAL_LOGIN_TITLE = "ERROR_SOCIAL_LOGIN_TITLE"
    static let ERROR_SOCIAL_LOGIN_MESSAGE = "ERROR_SOCIAL_LOGIN_MESSAGE"
    static let UPDATE_ALERT_TITLE = "UPDATE_ALERT_TITLE"
    static let UPDATE_MESSAGE = "UPDATE_MESSAGE"
    static let UPDATE_TITLE = "UPDATE_ALERT_TITLE"
    static let SESSION_NOT_EXISTED_MESSAGE = "SESSION_NOT_EXISTED_MESSAGE"
    static let CANCEL_REQUEST_BOOKSTOP_MESSAGE = "CANCEL_REQUEST_BOOKSTOP_MESSAGE"
    static let LEVEAVE_BOOKSTOP_MESSAGE = "LEVEAVE_BOOKSTOP_MESSAGE"
    static let DOING_JOIN_BOOKSTOP_MESSAGE = "DOING_JOIN_BOOKSTOP_MESSAGE"
    static let NOTIFICATION_TITLE = "NOTIFICATION_TITLE"
    static let YOUR_SEND_MESSAGE = "YOUR_SEND_MESSAGE"
    static let SERVER_ERROR_MESSAGE = "SERVER_ERROR_MESSAGE"
    static let CANCEL_ERROR_TITLE = "CANCEL_ERROR_TITLE"
}

extension Gat.Text.TabBar {

}

extension Gat.Text.Home {
    static let NEARBY_USER_TITLE = "NEARBY_USER_TITLE_HOME"
    static let MORE_TITLE = "MORE_TITLE_HOME"
    static let BOOK_SHARING_TITLE = "BOOK_SHARING_TITLE_HOME"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_HOME"
    static let SETTING_ALERT_TITLE = "SETTING_ALERT_TITLE_HOME"
    static let CANCEL_ALERT_TITLE = "CANCEL_ALERT_TITLE_HOME"
    //static let OK_ALERT_TITLE = NSLocalizedString("OK_ALERT_TITLE_HOME", bundle: Gat.bundle, comment: "Ok")
    static let ERROR_BOOKS_EMPTY_MESSAGE = "ERROR_BOOKS_EMPTY_MESSAGE_HOME"//NSLocalizedString("ERROR_BOOKS_EMPTY_MESSAGE_HOME", bundle: Gat.bundle, comment: "Book Empty!")
    static let NOT_FOUND_NEARBY_USER_MESSAGE = "NOT_FOUND_NEARBY_USER_MESSAGE_HOME"//NSLocalizedString("NOT_FOUND_NEARBY_USER_MESSAGE_HOME", bundle: Gat.bundle, comment: "Not found neary by user!")
    
    static let EXPLORATION_TITLE = "EXPLORATION_TITLE_HOME"
    static let PROFILE_EXPLORATION = "PROFILE_EXPLORATION_HOME"
    static let BOOKSTOP_EXPLORATION = "BOOKSTOP_EXPLORATION_HOME"
    static let FAN_PAGE_EXPLORATION = "FAN_PAGE_EXPLORATION_HOME"
    static let TOP_BORROW_BOOK_TITLE = "TOP_BORROW_BOOK_HOME"
    static let NEW_REVIEW_TITLE = "NEW_REVIEW_TITLE_HOME"
    static let RECOMMEND_BY_GAT = "RECOMMEND_BY_GAT_HOME"
    static let HOT_WRITTERS_ON_GAT = "HOT_WRITTERS_ON_GAT_HOME"
    static let BASE_ON_READ_ARTICLE = "BASE_ON_READ_ARTICLE_HOME"
    static let TRENDING_REVIEW = "TRENDING_REVIEW_HOME"
    static let TRENDING_ARTICLE = "TRENDING_ARTICLE_HOME"
    static let NEARBY_BOOKSTOP_TITLE = "NEARBY_BOOKSTOP_HOME"
    static let SUCCESS_TITLE = "SUCCESS_HOME"
    static let ADD_BOOKMARK_MESSAGE = "ADD_BOOKMARK_HOME"
    static let REMOVE_BOOKMARK_MESSAGE = "REMOVE_BOOKMARK_MESSAGE"
    static let COMMUNITY_TITLE = "COMMUNITY_TITLE"
}

extension Gat.Text.Category {
    static let ALL_CATEGORY_TITLE = "ALL_CATEGORY_TITLE"
    static let LITERATURE_CATEGORY_TITLE = "LITERATURE_CATEGORY_TITLE"
    static let SKILL_CATEGORY_TITLE = "SKILL_CATEGORY_TITLE"
    static let ECONOMIC_CATEGORY_TITLE = "ECONOMIC_CATEGORY_TITLE"
    static let HISTORY_AND_GEOGRAPHY_CATEGORY_TITLE = "HISTORY_AND_GEOGRAPHY_CATEGORY_TITLE"
    static let ART_CATEGORY_TITLE = "ART_CATEGORY_TITLE"
    static let RELIGION_CATEGORY_TITLE = "RELIGION_CATEGORY_TITLE"
    static let CHILDREN_CATEGORY_TITLE = "CHILDREN_CATEGORY_TITLE"
    static let COMIC_CATEGORY_TITLE = "COMIC_CATEGORY_TITLE"
    static let SCIENCE_CATEGORY_TITLE = "SCIENCE_CATEGORY_TITLE"
    static let TEXTBOOK_CATEGORY_TITLE = "TEXTBOOK_CATEGORY_TITLE"
    static let FOREIGN_LANGUAGE_CATEGORY_TITLE = "FOREIGN_LANGUAGE_CATEGORY_TITLE"
    static let SYLLABUS_CATEGORY_TITLE = "SYLLABUS_CATEGORY_TITLE"
    static let MOM_AND_BABY_CATEGORY_TITLE = "MOM_AND_BABY_CATEGORY_TITLE"
    static let SYNTHESIS_CATEGORY_TITLE = "SYNTHESIS_CATEGORY_TITLE"
    static let MAGAZINE_CATEGORY_TITLE = "MAGAZINE_CATEGORY_TITLE"
}

extension Gat.Text.NearByUser {
    static let NEARBY_USER_TITLE = "NEARBY_USER_TITLE"
    static let NOT_FOUND_NEARBY_USER_MESSAGE = "NOT_FOUND_NEARBY_USER_MESSAGE_NEARBYUSER"
    static let RESULT_HEADER_TITLE = "RESULT_HEADER_TITLE_NEARBYUSER"
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_NEARBYUSER"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_NEARBYUSER"
    static let SETTING_ALERT_TITLE = "SETTING_ALERT_TITLE_NEARBYUSER"
    static let CANCEL_ALERT_TITLE = "CANCEL_ALERT_TITLE_NEARBYUSER"
}

extension Gat.Text.Search {
    static let SEARCH_TITLE = "SEARCH_TITLE"
    static let SEARCH_BOOK_TITLE = "SEARCH_BOOK_TITLE_SEARCH"
    static let SEARCH_AUTHOR_TITLE = "SEARCH_AUTHOR_TITLE_SEARCH"
    static let SEARCH_USER_TITLE = "SEARCH_USER_TITLE_SEARCH"
    static let CANCEL_SEARCH_TITLE = "CANCEL_SEARCH_TITLE_SEARCH"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_SEARCH"
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_SEARCH"
    static let NUMBER_SHARING_BOOK_TITLE = "NUMBER_SHARING_BOOK_TITLE_SEARCH"
    static let NUMBER_REVIEW_BOOK_TITLE = "NUMBER_REVIEW_BOOK_TITLE_SEARCH"
    static let NUMBER_USER_SHARING_BOOK_TITLE = "NUMBER_USER_SHARING_BOOK_TITLE"
    static let NO_AUTHOR_TITLE = "NO_AUTHOR_TITLE_SEARCH"
    static let RESULT_SEARCH_TITLE = "RESULT_SEARCH_TITLE_SEARCH"
    static let ADD_NEW_BOOK_TITLE = "ADD_NEW_BOOK_SEARCH"
}

extension Gat.Text.BookDetail {
    static let BOOK_DETAIL_TITLE = "BOOK_DETAIL_TITLE"
    static let BOOK_DESCRIPTION_TITLE = "BOOK_DESCRIPTION_TITLE_BOOKDETAIL"
    static let REVIEW_BOOK_TITLE = "REVIEW_BOOK_TITLE_BOOKDETAIL"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_BOOKDETAIL"
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_BOOKDETAIL"
    static let CANCEL_ALERT_TITLE = "CANCEL_ALERT_TITLE_BOOKDETAIL"
    static let EDIT_REVIEW_TITLE = "EDIT_REVIEW_TITLE_BOOKDETAIL"
    static let WRITE_REVIEW_TITLE = "WRITE_REVIEW_TITLE_BOOKDETAIL"
    static let ADD_BOOK_TITLE = "ADD_BOOK_TITLE_BOOKDETAIL"
    static let BORROW_BOOK_TITLE = "BORROW_BOOK_TITLE_BOOKDETAIL"
    static let MORE_TITLE = "MORE_TITLE_BOOKDETAIL"
    static let BOOK_INFO_TITLE = "BOOK_INFO_TITLE_BOOKDETAIL"
    static let BUY_BOOK_TITLE = "BUY_BOOK_TITLE_BOOKDETAIL"
    static let MY_REVIEW_TITLE = "MY_REVIEW_TITLE_BOOKDETAIL"
    static let STOCKING_TITLE = "STOCKING_TITLE_BOOKDETAIL"
    static let OUT_OF_STOCK_TITLE = "OUT_OF_STOCK_TITLE_BOOKDETAIL"
    static let ADD_BOOKSHELF_MESSAGE = "ADD_BOOKSHELF_MESSAGE_BOOKDETAIL" //Do you want add this book to bookshelf?
    static let SUCCEEDED = "SUCCEEDED_BOOKDETAIL" // Succeeded
    static let ADD_BOOK_SUCCEEDED_MESSAGE = "ADD_BOOK_SUCCEEDED_MESSAGE_BOOKDETAIL"
}

extension Gat.Text.AddBook {
    static let ADD_BOOK_TITLE = "ADD_BOOK_TITLE"
    static let NUMBER_BOOK_TITLE = "NUMBER_BOOK_TITLE_ADDBOOK"
    static let ALLOW_SHARING_TITLE = "ALLOW_SHARING_TITLE_ADDBOOK"
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_ADDBOOK"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_ADDBOOK"
    static let YES_ALERT_TITLE = "YES_ALERT_TITLE_ADDBOOK"
    static let NO_ALERT_TITLE = "NO_ALERT_TITLE_ADDBOOK"
    static let CANCEL_ADDBOOK_MESSAGE = "CANCEL_ADDBOOK_MESSAGE_ADDBOOK"
    static let NOTIFICATION_CANCEL_ADDBOOK = "NOTIFICATION_CANCEL_ADDBOOK"
}

extension Gat.Text.Comment {
    static let RATE_TITLE = "RATE_TITLE_COMMENT"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_COMMENT"
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_COMMENT"
    static let YES_ALERT_TITLE = "YES_ALERT_TITLE_COMMENT"
    static let NO_ALERT_TITLE = "NO_ALERT_TITLE_COMMENT"
    static let CANCEL_COMMENT_MESSAGE = "CANCEL_COMMENT_MESSAGE_COMMENT"
    static let NOTIFICATION_CANCEL_COMMENT = "NOTIFICATION_CANCEL_COMMENT"
    static let EDIT_PLACEHOLDER = "EDIT_PLACEHOLDER_COMMENT"
}

extension Gat.Text.ListSharingBook {
    static let BOOKSELF_TITLE = "BOOKSELF_TITLE"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_LISTBOOKSHARING"
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_LISTBOOKSHARING"
    static let SORT_BY_TITLE = "SORT_BY_TITLE_LISTBOOKSHARING"
    static let BORROW_TITLE = "BORROW_TITLE_LISTBOOKSHARING"
    static let ON_HOLD_TITLE = "ON_HOLD_TITLE_LISTBOOKSHARING"
    static let BEING_BORROWED_STATUS_TITLE = "BEING_BORROWED_STATUS_TITLE_LISTBOOKSAHRING"
    static let ON_HOLD_AGREE_STATUS_TITLE = "ON_HOLD_AGREE_STATUS_TITLE_LISTBOOKSHARING"
    static let ON_HOLD_RETURN_STATUS_TITLE = "ON_HOLD_RETURN_STATUS_TITLE_LISTBOOKSHARING"
    static let DOING_CONTACT_STATUS_TITLE = "DOING_CONTACT_STATUS_TITLE_LISTBOOKSHARING"
    static let BORROWING_STATUS_TITLE = "BORROWING_STATUS_TITLE_LISTBOOKSHARING"
    static let READ_IN_PLACE_STATUS_TITLE = "READ_IN_PLACE_STATUS_TITLE_LISTBOOKSHARING"
    static let LIMITED_BORROW_TITLE = "LIMITED_BORROW_TITLE_LISTBOOKSHARING"
    static let BOOKSTOP_MEMBER_ONLY_TITLE = "BOOKSTOP_MEMBER_ONLY_TITLE_LISTBOOKSHARING"
}

extension Gat.Text.SortByListSharingBook {
    static let SORT_BY_TITLE = "SORT_BY_TITLE_SORTBY"
    static let UPTIME_STATUS_TITLE = "UPTIME_STATUS_TITLE_SORTBY"
    static let DISTANCE_STATUS_TITLE = "DISTANCE_STATUS_TITLE_SORTBY"
}

extension Gat.Text.Bookstop {
    static let READ_IN_PLACE_STATUS_TITLE = "READ_IN_PLACE_STATUS_TITLE_BOOKSTOP"
    static let SEARCH_BOOK_PLACEHOLDER = "SEARCH_BOOK_BOOKSTOP"
    static let BOOK_TITLE = "BOOK_BOOKSTOP"
    static let BOOK_SPACE_TITLE = "BOOK_SPACE_BOOKSTOP"
}

extension Gat.Text.Message {
    static let EMPTY_MESSAGE_TITLE = "EMPTY_MESSAGE_TITLE_LISTMESSAGE"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_LISTMESSAGE"
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_LISTMESSAGE"
    static let SEND_MESSAGE_TITLE = "SEND_MESSAGE_TITLE_MESSAGE"
    static let PLACEHOLDER_MESSAGE_TITLE = "PLACEHOLDER_MESSAGE_TITLE_MESSAGE"
    static let ERROR_SEND_MESSAGE = "ERROR_SEND_MESSAGE"
    static let RECOMMEND_MESSAGE_1 = "RECOMMEND_MESSAGE_1"
    static let RECOMMEND_MESSAGE_2 = "RECOMMEND_MESSAGE_2"
    static let RECOMMEND_MESSAGE_3 = "RECOMMEND_MESSAGE_3"
    static let RECOMMEND_MESSAGE_4 = "RECOMMEND_MESSAGE_4"
    static let READ_STATUS = "READ_STATUS_MESSAGE"
    static let YOURSELF = "YOURSELF_MESSAGE"
}

extension Gat.Text.Notification {
    static let NOTIFICATION_TITLE = "NOTIFICATION_TITLE"
    static let MESSAGE_TITLE = "MESSAGE_TITLE"
    static let NOTIFICATION_EMPTY_TITLE = "NOTIFICATION_EMPTY_TITLE_NOTIFICATION"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_NOTIFICATION"
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_NOTIFICATION"
    
    struct Code {}
}

extension Gat.Text.Notification.Code {
    static let EMPTY_NOTIFICATIONS_MESSAGE = "EMPTY_NOTIFICATIONS_MESSAGE"
    static let NOTIFICATION_TYPE_0_TITLE = "NOTIFICATION_TYPE_0_TITLE"
    static let NOTIFICATION_TYPE_1_TITLE = "NOTIFICATION_TYPE_1_TITLE"
    static let NOTIFICATION_TYPE_10_TITLE = "NOTIFICATION_TYPE_10_TITLE"
    static let NOTIFICATION_TYPE_11_TITLE = "NOTIFICATION_TYPE_11_TITLE"
    static let NOTIFICATION_TYPE_12_TITLE = "NOTIFICATION_TYPE_12_TITLE"
    static let NOTIFICATION_TYPE_13_TITLE = "NOTIFICATION_TYPE_13_TITLE"
    static let NOTIFICATION_TYPE_14_TITLE = "NOTIFICATION_TYPE_14_TITLE"
    static let NOTIFICATION_TYPE_15_TITLE = "NOTIFICATION_TYPE_15_TITLE"
    static let NOTIFICATION_TYPE_16_TITLE = "NOTIFICATION_TYPE_16_TITLE"
    static let NOTIFICATION_TYPE_17_TITLE = "NOTIFICATION_TYPE_17_TITLE"
    static let NOTIFICATION_TYPE_18_TITLE = "NOTIFICATION_TYPE_18_TITLE"
    static let NOTIFICATION_TYPE_19_TITLE = "NOTIFICATION_TYPE_19_TITLE"
    static let NOTIFICATION_TYPE_20_TITLE = "NOTIFICATION_TYPE_20_TITLE"
    static let NOTIFICATION_TYPE_21_TITLE = "NOTIFICATION_TYPE_21_TITLE"
    static let NOTIFICATION_TYPE_120_TITLE = "NOTIFICATION_TYPE_120_TITLE"
    static let NOTIFICATION_TYPE_121_TITLE = "NOTIFICATION_TYPE_121_TITLE"
    static let NOTIFICATION_TYPE_122_TITLE = "NOTIFICATION_TYPE_122_TITLE"
    static let NOTIFICATION_TYPE_123_TITLE = "NOTIFICATION_TYPE_123_TITLE"
    static let NOTIFICATION_TYPE_200_TITLE = "NOTIFICATION_TYPE_200_TITLE"
    static let NOTIFICATION_TYPE_201_TITLE = "NOTIFICATION_TYPE_201_TITLE"
    static let NOTIFICATION_TYPE_202_TITLE = "NOTIFICATION_TYPE_202_TITLE"
    static let NOTIFICATION_TYPE_203_TITLE = "NOTIFICATION_TYPE_203_TITLE"
    static let NOTIFICATION_TYPE_301_TITLE = "NOTIFICATION_TYPE_301_TITLE"
    static let NOTIFICATION_TYPE_500_TITLE = "NOTIFICATION_TYPE_500_TITLE"
    static let NOTIFICATION_TYPE_502_TITLE = "NOTIFICATION_TYPE_502_TITLE"
    static let NOTIFICATION_TYPE_600_TITLE = "NOTIFICATION_TYPE_600_TITLE"
    static let NOTIFICATION_TYPE_800_TITLE = "NOTIFICATION_TYPE_800_TITLE"
    static let NOTIFICATION_TYPE_801_TITLE = "NOTIFICATION_TYPE_801_TITLE"
    static let NOTIFICATION_TYPE_802_TITLE = "NOTIFICATION_TYPE_802_TITLE"
    static let NOTIFICATION_TYPE_803_TITLE = "NOTIFICATION_TYPE_803_TITLE"
    static let NOTIFICATION_TYPE_900_TITLE = "NOTIFICATION_TYPE_900_TITLE"
    static let NOTIFICATION_TYPE_901_TITLE = "NOTIFICATION_TYPE_901_TITLE"
    static let NOTIFICATION_TYPE_902_TITLE = "NOTIFICATION_TYPE_902_TITLE"
    static let NOTIFICATION_TYPE_903_TITLE = "NOTIFICATION_TYPE_903_TITLE"
    static let NOTIFICATION_TYPE_904_TITLE = "NOTIFICATION_TYPE_904_TITLE"
    static let NOTIFICATION_TYPE_905_TITLE = "NOTIFICATION_TYPE_905_TITLE"
    static let NOTIFICATION_TYPE_906_TITLE = "NOTIFICATION_TYPE_906_TITLE"
    static let NOTIFICATION_TYPE_907_TITLE = "NOTIFICATION_TYPE_907_TITLE"
    static let NOTIFICATION_TYPE_908_TITLE = "NOTIFICATION_TYPE_908_TITLE"
    static let NOTIFICATION_TYPE_909_TITLE = "NOTIFICATION_TYPE_909_TITLE"
    static let NOTIFICATION_TYPE_910_TITLE = "NOTIFICATION_TYPE_910_TITLE"
}

extension Gat.Text.RequestDetailBorrower {
    static let BORROW_TITLE = "BORROW_TITLE"
    static let ON_HOLD_TITLE = "ON_HOLD_TITLE"
    static let ON_HOLD_MESSAGE = "ON_HOLD_MESSAGE_REQUESTDETAILBORROWER"
    static let SEND_REQUEST_TO_TITLE = "SEND_REQUEST_TO_REQUESTDETAILBORROWER"
    static let SEND_MESSAGE = "SEND_MESSAGE_REQUESTDETAILBORROWER"
    static let INTEND_RETURN_MESSAGE = "INTEND_RETURN_MESSAGE_REQUESTDETAILBORROWER"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_REQUESTDETAILBORROWER"
    static let SEND_REQUEST_TITLE = "SEND_REQUEST_TITLE_REQUESTDETAILBORROWER"
    static let REVIEW_BOOK_TITLE = "REVIEW_BOOK_TITLE_REQUESTDETAILBORROWER"
    static let BORROW_FORMAT_MESSAGE = "BORROW_FORMAT_MESSAGE_REQUESTDETAILBORROWER"
    static let ONHOLD_FORMAT_MESSAGE = "ONHOLD_FORMAT_MESSAGE_REQUESTDETAILBORROWER"
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_REQUESTDETAILBORROWER"
}

extension Gat.Text.UserProfile {
    
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_USERPROFILE"
    
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_USERPROFILE"
    
    static let EDIT_TITLE = "EDIT_TITLE_USERPROFILE"
    
    struct BookInstance {}
    
    struct Review {}
    
    struct Request {}
}

extension Gat.Text.UserProfile.BookInstance {
    static let BOOK_INSTANCE_TITLE = "BOOK_INSTANCE_TITLE_BOOKUSERPROFILE"
    static let BORROW_STATUS_TITLE = "BORROW_STATUS_TITLE_BOOKUSERPROFILE"
    static let BORROW_BY_TITLE = "BORROW_BY_TITLE_BOOKUSERPROFILE"
    static let SHARINGBOOK_TITLE = "SHARING_BOOK_BOOKUSERPROFILE"
    static let NOT_SHARING_BOOK_TITLE = "NOT_SHARING_BOOK_TITLE_BOOKUSERPROFILE"
    static let LOST_BOOK_TITLE = "LOST_BOOK_TITLE_BOOKUSERPROFILE"
    static let YES_ALERT_TITLE = "YES_ALERT_TITLE_BOOKUSERPROFILE"
    static let NO_ALERT_TITLE = "NO_ALERT_TITLE_BOOKUSERPROFILE"
    static let REMOVE_ALERT_TITLE = "REMOVE_ALERT_TITLE_BOOKUSERPROFILE"
    static let REMOVE_MESSAGE = "REMOVE_MESSAGE_BOOKUSERPROFILE"
    static let ADD_BOOK_MESSAGE = "ADD_BOOK_MESSAGE_USERPROFILE"
}

extension Gat.Text.UserProfile.Review {
    static let REVIEW_TITLE = "REIVEW_TITLE_REVIEWUSERPROFILE"
    static let RATING_TITLE = "RATING_TITLE_REVIEWUSERPROFILE"
    static let MORE_TITLE = "MORE_TITLE_REVIEWUSERPROFILE"
    static let EDIT_ALERT_TITLE = "EDIT_ALERT_TITLE_REVIEWUSERPROFILE"
    static let REMOVE_ALERT_TITLE = "REMOVE_ALERT_TITLE_REVIEWUSERPROFILE"
    static let CANCEL_ALERT_TITLE = "CANCEL_ALERT_TITLE_REVIEWUSERPROFILE"
    static let YES_ALERT_TITLE = "YES_ALERT_TITLE_REVIEWUSERPROFILE"
    static let NO_ALERT_TITLE = "NO_ALERT_TITLE_REVIEWUSERPROFILE"
    static let REMOVE_MESSAGE = "REMOVE_MESSAGE_REVIEWUSERPROFILE"
    static let NOTIFICATION_REMOVE_REVIEW = "NOTIFICATION_REMOVE_REVIEW_REVIEWUSERPROFILE"
}

extension Gat.Text.UserProfile.Request {
    static let REQUEST_TITLE = "REQUEST_TITLE_REQUESTUSERPROFILE"
    static let REJECT_TITLE = "REJECT_TITLE_REQUESTUSERPROFILE"
    static let ACCEPT_TITLE = "ACCEPT_TITLE_REQUESTUSERPROFILE"
    static let REQUEST_INT_COMMING_TITLE = "REQUEST_INT_COMMING_TITLE_REQUESTUSERPROFILE"
    static let REQUEST_OUT_GOING_TITLE = "REQUEST_OUT_GOING_TITLE_REQUESTUSERPROFILE"
    static let OWNER_REQUEST_TITLE = "OWNER_REQUEST_TITLE_REQUESTUSERPROFILE"
    static let BORROWER_REQUEST_TITLE = "BORROWER_REQUEST_TITLE_REQUESTUSERPROFILE"
    static let WAITING_CONFIRM_STATUS = "WAITING_CONFIRM_STATUS_REQUESTUSERPROFILE"
    static let ON_HOLD_STATUS = "ON_HOLD_STATUS_REQUESTUSERPROFILE"
    static let CONTACTING_STATUS = "CONTACTING_REQUESTUSERPROFILE"
    static let BORROWING_STATUS = "BORROWING_STATUS_REQUESTUSERPROFILE"
    static let RETURNED_STATUS = "RETURNED_STATUS_REQUESTUSERPROFILE"
    static let REJECTED_STATUS = "REJECTED_STATUS_REQUESTUSERPROFILE"
    static let CANCELLED_STATUS = "CANCELLED_STATUS_REQUESTUSERPROFILE"
    static let UNRETURNED_STATUS = "UNRETURNED_STATUS_REQUESTUSERPROFILE"
    static let OTHER_STATUS = "OHTER_STATUS_REQUESTUSERPROFILE"
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_REQUESTUSERPROFILE"
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_REQUESTUSERPROFILE"
    static let REQUEST_TO_BORROW_BOOK_FILTER = "REQUEST_TO_BORROW_BOOK_FILTER_REQUESTUSERPROFILE"
    static let STATUS_FILTER = "STATUS_FILTER_REQUESTUSERPROFILE"
}

extension Gat.Text.VistorUserProfile {
    static let ERROR_ALERT_TITLE = "ERROR_ALERT_TITLE_VISTORUSERPROFILE"
    
    static let OK_ALERT_TITLE = "OK_ALERT_TITLE_VISTORUSERPROFILE"
    
    struct BookSharing {}
    
    struct Review {}
}

extension Gat.Text.VistorUserProfile.BookSharing {
    static let BOOK_SHARING_TITLE = "BOOK_SHARING_TITLE_BOOKVISTORUSERPROFILE"
    static let DOING_BORROWED_STATUS = "DOING_BORROWED_STATUS_BOOKVISTORUSERPROFILE"
    static let WATING_CONFIRM_STATUS = "WATING_CONFIRM_STATUS_BOOKVISTORUSERPROFILE"
    static let ON_HOLD_STATUS = "ON_HOLD_STATUS_BOOKVISTORUSERPROFILE"
    static let BORROWING_STATUS = "BORROWING_STATUS_BOOKVISTORUSERPROFILE"
    static let CONTACTING_STATUS = "CONTACTING_STATUS_BOOKVISTORUSERPROFILE"
    static let BORROW_BOOK_TITLE = "BORROW_BOOK_TITLE_BOOKVISTORUSERPROFILE"
    static let WAITING_BORROW_BOOK_TITLE = "WAITING_BORROW_BOOK_TITLE_BOOKVISTORUSERPROFILE"
}

extension Gat.Text.VistorUserProfile.Review {
    static let REVIEW_TITLE = "REVIEW_TITLE_REVIEWVISTORUSERPROFILE"
    static let RATING_TITLE = "RATING_TITLE_REVIEWVISTORUSERPROFILE"
    static let MORE_TITLE = "MORE_TITLE_REVIEWVISTORUSERPROFILE"
}

extension Gat.Text.StartApp {
    static let OVERVIEW_APP_TITLE = "OVERVIEW_APP_TITLE_STARTAPP"
    static let REGISTER_TITLE = "REGISTER_TITLE_STARTAPP"
    static let LOGIN_TITLE = "LOGIN_TITLE_STARTAPP"
    static let OVERVIEW_APP_TITLE_STARTAPP = "OVERVIEW_APP_TITLE_STARTAPP"
    static let START_PAGE_CAROUSEL_DATA = "START_PAGE_CAROUSEL_DATA"
}

extension Gat.Text.Login {
    static let LOGIN_TITLE = "LOGIN_TITLE"
    static let PASSWORD_PLACEHOLDER = "PASSWORD_PLACEHOLDER_LOGIN"
    static let FORGOT_PASSWORD_TITLE = "FORGOT_PASSWORD_TITLE_LOGIN"
    static let LOGIN_SOCIAL_TITLE = "LOGIN_SOCIAL_TITLE_LOGIN"
    static let SESSION_INVALID_MESSAGE = "SESSION_INVALID_MESSAGE_LOGIN"
    static let TOKEN_FIREBASE_INVALID_MESSAGE = "TOKEN_FIREBASE_INVALID_MESSAGE_LOGIN"
    static let REGISTER_NOW = "REGISTER_NOW_LOGIN"
    static let HAVE_NOT_ACCOUNT = "HAVE_NOT_ACCOUNT_LOGIN"
    static let MESSAGE_EMAIL = "MESSAGE_EMAIL_LOGIN"
    static let MESSAGE_PASSWORD = "MESSAGE_PASSWORD_LOGIN"
}

extension Gat.Text.Register {
    static let REGISTER_TITLE = "REGISTER_TITLE"
    static let REGISTER_SOCIAL_TITLE = "REGISTER_SOCIAL_TITLE_REGISTER"
    static let EMAIL_ADDRESS_PLACEHOLDER = "ADDRESS_EMAIL_PLACEHOLDER_REGISTER"
    static let PASSWORD_PLACEHOLDER = "PASSWORD_PLACEHOLDER_REGISTER"
    static let FACEBOOK_TITLE = "Facebook"
    static let TWITTER_TITLE = "Twitter"
    static let GOOGLE_TITLE = "Google"
    static let SESSION_INVALID_MESSAGE = "SESSION_INVALID_MESSAGE_REGISTER"
    static let TOKEN_FIREBASE_INVALID_MESSAGE = "TOKEN_FIREBASE_INVALID_MESSAGE_REGISTER"
    static let CONFIRM_EMPTY_MESSAGE = "CONFIRM_EMPTY_MESSAGE_REGISTER"
    static let COMFIRM_NOT_EQUAL_PASSWORD_MESSAGE = "COMFIRM_NOT_EQUAL_PASSWORD_MESSAGE_REGISTER"
    static let ALREADY_HAVE_ACCOUNT = "ALREADY_HAVE_ACCOUNT_REGISTER"
    static let LOGIN_NOW = "LOGIN_NOW_REGISTER"
    static let CONFIRM_PASSWORD = "CONFIRM_PASSWORD_REGISTER"
    static let COMFIRM_PASSWORD_PLACEHOLDER = "COMFIRM_PASSWORD_PLACEHOLDER_REGISTER"
}

extension Gat.Text.Map {
    static let ADD_LOCATION_PLACEHOLDER = "ADD_LOCATION_PLACEHOLDER_MAP"
    static let OK_TITLE = "OK_TITLE_MAP"
    static let SKIP_TITLE = "SKIP_TITLE_MAP"
    static let SAVE_ADDRESS_TITLE = "SAVE_ADDRESS_TITLE_MAP"
}

extension Gat.Text.FavouriteCategory {
    static let FAVOURITE_CATEGORY_TITLE = "FAVOURITE_CATEGORY_TITLE"
    static let OK_TITLE = "OK_TITLE_FAVOURITECATEGORY"
    static let SAVE_TITLE = "SAVE_TITLE_FAVOURITECATEGORY"
    static let SKIP_TITLE = "SKIP_TITLE_FAVOURITECATEGORY"
}

extension Gat.Text.ForgotPassword {
    static let FORGOT_PASSWORD_TITLE = "FORGOT_PASSWORD_TITLE"
    static let MESSAGE_FORGOT = "MESSAGE_FORGOT_FORGOTPASSWORD"
    static let EMAIL_ADDRESS_PLACEHOLDER = "EMAIL_ADDRESS_PLACEHOLDER_FORGOTPASSWORD"
    static let SEND_EMAIL_TITLE = "SEND_EMAIL_TITLE_FORGOTPASSWORD"
    static let ACCOUNT_INVALID_MESSAGE = "ACCOUNT_INVALID_MESSAGE_FORGOTPASSWORD"
    static let SESSION_INVALID_MESSAGE = "SESSION_INVALID_MESSAGE_FORGOTPASSWORD"
    static let TOKEN_FIREBASE_INVALID_MESSAGE = "TOKEN_FIREBASE_INVALID_MESSAGE_FORGOTPASSWORD"
}

extension Gat.Text.ResetPasswordForSocial {
    static let FORGOT_PASSWORD_TITLE = "FORGOT_PASSWORD_TITLE"
    static let MESSAGE_FORGOT = "MESSAGE_FORGOT_RESETPASSWORDFORSOCIAL"
    static let NEW_PASSWORD_PLACEHOLDER = "NEW_PASSWORD_PLACEHOLDER_RESETPASSWORDFORSOCIAL"
    static let CHANGE_PASSWORD_TITLE = "CHANGE_PASSWORD_TITLE_RESETPASSWORDFORSOCIAL"
}

extension Gat.Text.ConfirmPassword {
    static let FORGOT_PASSWORD_TITLE = "FORGOT_PASSWORD_TITLE"
    static let MESSAGE_FORGOT = "MESSAGE_FORGOT_CONFIRMPASSWORD"
    static let CODE_PLACEHOLDER = "CODE_PLACEHOLDER_CONFIRMPASSWORD"
    static let CHANGE_PASSWORD_TITLE = "CHANGE_PASSWORD_TITLE_CONFIRMPASSWORD"
}

extension Gat.Text.ResetPassword {
    static let FORGOT_PASSWORD_TITLE = "FORGOT_PASSWORD_TITLE"
    static let MESSAGE_FORGOT = "MESSAGE_FORGOT_RESETPASSWORD"
    static let NEW_PASSWORD_PLACEHOLDER = "NEW_PASSWORD_PLACEHOLDER_RESETPASSWORD"
    static let CHANGE_PASSWORD_TITLE = "CHANGE_PASSWORD_TITLE_RESETPASSWORD"
    static let SESSION_INVALID_MESSAGE = "SESSION_INVALID_MESSAGE_RESETPASSWORD"
    static let TOKEN_FIREBASE_INVALID_MESSAGE = "TOKEN_FIREBASE_INVALID_MESSAGE_RESETPASSWORD"
}

extension Gat.Text.Barcode {
    static let SEARCH_TITLE_BARCODE = "SEARCH_TITLE_BARCODE"
    static let BARCODE_MESSAGE = "BARCODE_MESSAGE_BARCODE"
    static let TURN_ON_TITLE = "TURN_ON_TITLE_BARCODE"
    static let TURN_OFF_TITLE = "TURN_OFF_TITLE_BARCODE"
    static let CAN_NOT_SCAN_CODE_MESSAGE = "CAN_NOT_SCAN_CODE_MESSAGE_BARCODE"
}

extension Gat.Text.EditUser {
    static let EDIT_TITLE = "EDIT_TITLE"
    static let CANCEL_TITLE = "CANCEL_TITLE_EDITUSER"
    static let SAVE_TITLE = "SAVE_TITLE_EDITUSER"
    static let DONE_TITLE = "DONE_TITLE_EDITUSER"
    static let YOUR_NAME_PLACEHOLDER = "YOUR_NAME_PLACEHOLDER_EDITUSER"
    static let ADDRESS_TITLE = "ADDRESS_TITLE_EDITUSER"
    static let ABOUT_TITLE = "ABOUT_TITLE_EDITUSER"
    static let LIST_FAVOURITE_CATEGORY_TITLE = "LIST_FAVOURITE_CATEGORY_TITLE_EDITUSER"
    static let CHANGE_AVATAR_TITLE = "CHANGE_AVATAR_TITLE"
    static let MEMBER_BOOKSTOP_TITLE = "MEMBER_BOOKSTOP_EDITUSER"
    static let ADD_BOOKSTOP_TITLE = "ADD_BOOKSTOP_EDITUSER"
    static let CANCEL_REQUEST_TITLE = "CANCEL_REQUEST_EDITUSER"
    static let REMOVE_TITLE = "REMOVE_EDITUSER"
    static let BOOKSTOP_PLACEHOLDER = "BOOKSTOP_PLACEHOLDER_EDITUSER"
}

extension Gat.Text.Setting {
    static let SETTING_TITLE = "SETTING_TITLE"
    static let EDIT_USER_INFO_TITLE = "EDIT_USER_INFO_TITLE_SETTING"
    static let ADD_EMAIL_AND_PASSWORD_TITLE = "ADD_EMAIL_AND_PASSWORD_TITLE_SETTING"
    static let CHANGE_PASSWORD_TITLE = "CHANGE_PASSWORD_TITLE_SETTING"
    static let LOGOUT_TITLE = "LOGOUT_TITLE_SETTING"
    static let CREATE_ACCOUNT_TITLE = "CREATE_ACCOUNT_TITLE_SETTING"
    static let INFO_SOCIAL_INVALID_MESSAGE = "INFO_SOCIAL_INVALID_MESSAGE_SETTING"
    static let SESSION_NOT_EXISTED_MESSAGE = "SESSION_NOT_EXISTED_MESSAGE_SETTING"
    static let BOOKSHELF_GAT_UP = "BOOK_SHELF_GAT_UP_SETTING"//"Tủ sách GAT-UP"
    static let BOOKSHELF_GAT_UP_DESCRIPTION = "BOOK_SHELF_GAT_UP_DESCRIPTION_SETTING" //Khám phá ngay!
    static let FACEBOOK_TITLE = "Facebook"
    static let TWITTER_TITLE = "Twitter"
    static let GOOGLE_TITLE = "Google"
    static let READING_HISTORY = "READING_HISTORY_SETTING"
    static let REVIEW_GAT = "REVIEW_GAT_SETTING"
    static let QUESTION = "QUESTION_SETTING"
    static let TERM_AND_POLICY = "TERM_AND_POLICY_SETTING"
    static let ABOUT_US = "ABOUT_US_SETTING"
}

extension Gat.Text.AddEmailAndPassword {
    static let ADD_EMAIL_AND_PASSWORD_TITLE = "ADD_EMAIL_AND_PASSWORD_TITLE"
    static let ADD_EMAIL_PLACEHOLDER = "ADD_EMAIL_PLACEHOLDER_ADDEMAILANDPASSWORD"
    static let PASSWORD_PLACEHOLDER = "PASSWORD_PLACEHOLDER_ADDEMAILANDPASSWORD"
}

extension Gat.Text.SocialNetwork {
    static let FACEBOOK_TITLE = "Facebook"
    static let TWITTER_TITLE = "Twitter"
    static let GOOGLE_TITLE = "Google"
    static let INFO_SOCIAL_INVALID_MESSAGE = "INFO_SOCIAL_INVALID_MESSAGE_SOCIALNETWORK"
    static let DISCONNECT_TITLE = "DISCONNECT_TITLE_SOCIALNETWORK"
    static let CONNECTING_ACCOUNT_TITLE = "CONNECTING_ACCOUNT_TITLE_SOCIALNETWORK"
}

extension Gat.Text.ChangePassword {
    static let CHANGE_PASSWORD_TITLE = "CHANGE_PASSWORD_TITLE"
    static let PASSWORD_INVALID_MESSAGE = "PASSWORD_INVALID_MESSAGE_CHANGEPASSWORD"
    static let PRESENT_PASSWORD_PLACEHOLDER = "PRESENT_PASSWORD_PLACEHOLDER_CHANGEPASSWORD"
    static let NEW_PASSWORD_PLACEHOLDER = "NEW_PASSWORD_PLACEHOLDER_CHANGEPASSWORD"
    static let CONFIRM_PASSWORD_PLACEHOLDER = "CONFIRM_PASSWORD_PLACEHOLDER_CHANGEPASSWORD"
    static let FORGOT_PASSWORD_TITLE = "FORGOT_PASSWORD_TITLE_CHANGEPASSWORD"
    static let PASSWORD_MESSAGE = "PASSOWRD_MESSAGE_CHANGEPASSWORD"
}

extension Gat.Text.OwnerRequestDetail {
    static let OWNER_REQUEST_DETAIL = "OWNER_REQUEST_DETAIL"
    static let ACCEPT_TITLE = "ACCEPT_STATUS_OWNERREQUESTDETAIL"
    static let REJECT_TITLE = "REJECT_STATUS_OWNERREQUESTDETAIL"
    static let ON_HOLD_STATUS = "ON_HOLD_STATUS_OWNERREQUESTDETAIL"
    static let ON_HOLD_MESSAGE = "ON_HOLD_MESSAGE_OWNERREQUESTDETAIL"
    static let CONTACT_STATUS = "CONTACT_STATUS_OWNERREQUESTDETAIL"
    static let BORROW_STATUS = "BORROW_STATUS_OWNERREQUESTDETAIL"
    static let REJECT_STATUS = "REJECT_STATUS_OWNERREQUESTDETAIL"
    static let RETURN_STATUS = "RETURN_STATUS_OWNERREQUESTDETAIL"
    static let DID_LOST_STATUS = "DID_LOST_STATUS_OWNERREQUESTDETAIL"
    static let DID_LOST_MESSAGE = "DID_LOST_MESSAGE_OWNERREQUESTDETAIL"
    static let CANCELLED_STATUS = "CANCELLED_STATUS_OWNERREQUESTDETAIL"
    static let REJECTED_STATUS = "REJECTED_STATUS_OWNERREQUESTDETAIL"
    static let BORROW_EXPECTATION_TIME_TITLE = "BORROW_EXPECTATION_TIME_TITLE_OWNERREQUESTDETAIL"
    static let NUMBER_REVIEW_TITLE = "NUMBER_REVIEW_TITLE_OWNERREQUESTDETAIL"
    static let SHARING_BOOKS_TITLE = "SHARING_BOOKS_TITLE_OWNERREQUESTDETAIL"
    static let SEND_REQUEST_BORROW_BOOK_TITLE = "SEND_REQUEST_BORROW_BOOK_TITLE_ONWERREQUESTDETAIL"
    static let DATE_SEND_REQUEST_TITLE = "DATE_SEND_REQUEST_TITLE_OWNERREQUESTDETAIL"
    static let DATE_START_BORROW_TITLE = "DATE_START_BORROW_TITLE_OWNERREQUESTDETAIL"
    static let DATE_RETURN_BOOK_TITLE = "DATE_RETURN_BOOK_TITLE_OWNERREQUESTDETAIL"
    static let DATE_REJECT_REQUEST_TITLE = "DATE_REJECT_REQUEST_TITLE_OWNERREQUESTDETAIL"
    static let DATE_CANCEL_REQUEST_TITLE = "DATE_CANCEL_REQUEST_TITLE_OWNERREQUESTDETAIL"
    static let SEND_MESSAGE_TO_TITLE = "SEND_MESSAGE_TO_TITLE_OWNERREQUESTDETAIL"
}

extension Gat.Text.BorrowerRequestDetail {
    static let BORROWER_REQUEST_DETAIL = "BORROWER_REQUEST_DETAIL"
    static let CANCEL_STATUS = "CANCEL_STATUS_BORROWERREQUESTDETAIL"
    static let ON_HOLD_STATUS = "ON_HOLD_STATUS_BORROWERREQUESTDETAIL"
    static let ON_HOLD_MESSAGE = "ON_HOLD_MESSAGE_BORROWERREQUESTDETAIL"
    static let CONTACT_STATUS = "CONTACT_STATUS_BORROWERREQUESTDETAIL"
    static let BORROW_STATUS = "BORROW_STATUS_BORROWERREQUESTDETAIL"
    static let DID_LOST_STATUS = "DID_LOST_STATUS_BORROWERREQUESTDETAIL"
    static let DID_LOST_MESSAGE = "DID_LOST_MESSAGE_BORROWERREQUESTDETAIL"
    static let RETURN_STATUS = "RETURN_STATUS_BORROWERREQUESTDETAIL"
    static let DID_CANCEL_STATUS = "DID_CANCEL_STATUS_BORROWERREQUESTDETAIL"
    static let BEING_REJECTED_STATUS = "BEING_REJECTED_STATUS_BORROWERREQUESTDETAIL"
    static let BORROW_EXPECTATION_TIME_TITLE = "BORROW_EXPECTATION_TIME_TITLE_BORROWERREQUESTDETAIL"
    static let NUMBER_REVIEW_TITLE = "NUMBER_REVIEW_TITLE_BORROWERREQUESTDETAIL"
    static let SHARING_BOOKS_TITLE = "SHARING_BOOKS_TITLE_BORROWERREQUESTDETAIL"
    static let YOU_SEND_REQUEST_BORROW_TITLE = "YOU_SEND_REQUEST_BORROW_TITLE_BORROWERREQUESTDETAIL"
    static let DATE_SEND_REQUEST_TITLE = "DATE_SEND_REQUEST_TITLE_BORROWERREQUESTDETAIL"
    static let DATE_START_BORROW_TITLE = "DATE_START_BORROW_TITLE_BORROWERREQUESTDETAIL"
    static let DATE_RETURN_BOOK_TITLE = "DATE_RETURN_BOOK_TITLE_BORROWERREQUESTDETAIL"
    static let DATE_REJECT_REQUEST_TITLE = "DATE_REJECT_REQUEST_TITLE_BORROWERREQUESTDETAIL"
    static let DATE_CANCEL_REQUEST_TITLE = "DATE_CANCEL_REQUEST_TITLE_BORROWERERQUESTDETAIL"
    static let SEND_MESSAGE_TO_TITLE = "SEND_MESSAGE_TO_TITLE_BORROWERERQUESTDETAIL"
}

extension Gat.Text.TopBorrowBook {
    static let TITLE_LABEL = "TOP_BORROW_BOOK"
    static let ADD_BOOK_TITLE = "ADD_BOOK_TITLE_TOPBORROWBOOK"
    static let BORROW_TITLE = "BORROW_TITLE_TOPBORROWBOOK"
}

extension Gat.Text.BookstopExplore {
    static let TITLE = "TITLE_BOOKSTOPEXPLORE"
    static let NEARBY_BOOKSTOP_TITLE = "NEARBY_BOOKSTOP_BOOKSTOPEXPLORE"
    static let NEW_BOOKSTOP_TITLE = "NEW_BOOKSTOP_BOOKSTOPEXPLORE"
}

extension Gat.Text.ReviewExplore {
    static let TITLE = "TITLE_REVIEWEXPLORE"
    static let TOP_REVIEWERS_TITLE = "TOP_REVIEWS_REVIEWEXPLORE"
    static let NEW_REVIEW_TITLE = "NEW_REVIEW_REVIEWEXPLORE"
}

extension Gat.Text.RequestBorrowerBookstop {
    static let TITLE = "TITLE_REQUESTBORROWERBOOKSTOP"
    static let YOU_BORROW_FROM_MESSAGE = "YOU_BORROW_MESSAGE_REQUESTBORROWERBOOKSTOP"
    static let FROM_MESSAGE = "FROM_MESSAGE_REQUESTBORROWERBOOKSTOP"
    static let MEMBERS_TITLE = "MEMBERS_TITLE_REQUESTBORROWERBOOKSTOP"
    static let BOOKS_TITLE = "BOOKS_TITLE_REQUESTBORROWERBOOKSTOP"
    static let DEADLINE_RETURN_BOOK_MESSAGE = "DEADLINE_RETURN_BOOK_MESSAGE_REQUESTBORROWERBOOKSTOP"//Bạn đã quá hạn 3 ngày trả sách!!!
    static let EXPECTED_TIME = "EXPECTED_TIME_REQUESTBORROWERBOOKSTOP" //Ngày dự định trả sách:
    static let RETURN_MESSAGE = "RETURN_MESSAGE_REQUESTBORROWERBOOKSTOP" //Bạn đã trả sách lại bookstop và đặt sách đúng vị trí chưa?
    static let CONFIRM = "CONFIRM_NOTIFICATION_REQUESTBORROWERBOOKSTOP"
}

extension Gat.Text.RequestBookstop {
    static let YOU_BORROWING_MESSAGE = "YOU_BORROWING_MESSAGE_REQUESTBOOKSTOP"
    static let EXPECTATION_TIME = "EXPECTATION_TIME_REQUESTBOOKSTOP"
    static let START_TITLE = "START_REQUESTBOOKSTOP"
    static let BORROW_TITLE = "BORROW_REQUESTBOOKSTOP"
    static let START_BORROW_TITLE = "START_BORROW_REQUESTBOOKSTOP"
    static let EXPECTATION_TIME_TITLE = "EXPECTATION_TIME_TITLE_REQUESTBOOKSTOP"
    static let JOIN_BOOKSTOP_MESSAGE = "JOIN_BOOKSTOP_MESSAGE_REQUESTBOOKSTOP"
    static let JOIN_TITLE = "JOIN_REQUESTBOOKSTOP"
    static let BOOK_INFO = "BOOK_INFO_REQUESTBOOKSTOP"
    static let BORROW_BOOK = "BORROW_BOOK_REQUESTBOOKSTOP"
    static let BORROWER_INFO = "BORROWER_INFO_REQUESTBOOKSTOP"
}

extension Gat.Text.BookstopOrganization {
    static let BOOKS_TITLE = "BOOKS_BOOKSTOPORGANIZATION"
    static let MEMBERS_TITLE = "MEMBERS_BOOKSTOPORGANIZATION"
    static let LEAVE_BOOKSTOP_SUCCESS_MESSAGE = "LEAVE_BOOKSTOP_SUCCESS_MESSAGE_BOOKSTOPORGANIZATION"
    static let CANCEL_REQUEST_SUCCESS_MESSAGE = "CANCEL_REQUEST_SUCCESS_MESSAGE_BOOKSTOPORGANIZATION"
    static let JOIN_MESSAGE = "JOIN_MESSAGE_BOOKSTOPORGANIZATION"
    static let SUCCESS_TITLE = "SUCCESS_TITLE_"
    static let BOOKSHELF_TITLE = "BOOKSHELF_TITLE_BOOKSTOPORGANIZATION"
    static let READING_CORNER_TITLE = "READING_CORNER_TITLE_BOOKSTOPORGANIZATION"
    static let MEMBER_ACTIVITIES_TITLE = "MEMBER_ACTIVITIES_TITLE_BOOKSTOPORGANIZATION"
    static let SHOW_ALL_TITLE = "SHOW_ALL_TITLE_BOOKSTOPORGANIZATION"
    static let MEMBER_BORROW_ACTIVITY = "MEMBER_ACTIVITY_BORROW_BOOKSTOPORGANIZATION"
    static let MEMBER_RETURN_ACTIVITY = "MEMBER_ACTIVITY_RETURN_BOOKSTOPORGANIZATION"
    static let LEAVE_TITLE = "LEAVE_BOOKSTOPORGANIZATION"
    static let CANCEL_TITLE = "CANCEL_BOOKSTOPORGANIZATION"
    static let JOIN_TITLE = "JOIN_BOOKSTOPORGANIZATION"
    static let HIDE_TITLE = "HIDE_BOOKSTOPORGANIZATION"
}

extension Gat.Text.BookstopOrganizaionShelve {
    static let SEARCH_PLACEHOLDER = "SEARCH_PLACEHOLDER_BOOKSTOPORGANIZATIONSHELVE"
    static let LIMITED_BORROW_TITLE = "LIMITED_BORROW_TITLE_BOOKSTOPORGANIZATIONSHELVE"
    static let BOOKSTOP_MEMBER_ONLY_TITLE = "BOOKSTOP_MEMBER_ONLY_BOOKSTOPORGANIZATIONSHELVE"
}

extension Gat.Text.JoinBookstop {
    static let TITLE = "TITLE_JOINBOOKSTOP"
    static let REQUEST_MESSAGE = "REQUEST_MESSAGE_JOINBOOKSTOP"
    static let JOIN_BOOKSTOP_SUCCESS_MESSAGE = "JOIN_BOOKSTOP_SUCCESS_MESSAGE_JOINBOOKSTOP" //Đã gửi thành công yêu cầu tham gia bookstop
}

extension Gat.Text.Language {
    static let TITLE = "LANGUAGE"
}

extension Gat.Text.Filterable {
    static let EMPTY_REVIEW = "EMPTY_REVIEW_FILTER" //ko co review
    static let NOT_EMPTY_REVIEW = "NOT_EMPTY_REVIEW_FILTER" // co review
    static let AVAILABLE_BOOK = "AVAILABLE_BOOK_FILTER" //sach co san
    static let NOT_AVAILABLE_BOOK = "NOT_AVAILABLE_BOOK_FILTER" // sach ko co san
    static let LOST_BOOK = "LOST_BOOK_FILTER"
    static let FILTER_TITLE = "FILTERABLE_TITLE" //loc
    static let FILTER_BUTTON = "FILTERABLE_BUTTON" //loc theo
    static let ACCEPT_FILTER_BUTTON = "ACCEPT_FILTERABLE_BUTTON" //xac nhan loc
    static let ALL_FILTERABLE = "ALL_FILTERABLE";
}

extension Gat.Text.AddNewBook {
    static let ADD_NEW_BOOK_TITLE = "ADD_NEW_BOOK_TITLE" //Thêm thông tin sách
    static let BOOK_NAME = "BOOK_NAME_ADDNEWBOOK" //Tên sách
    static let SEND = "SEND_ADDNEWBOOK" //Gửi
    static let DESCRIPTION_BOOK = "DESCRIPTION_BOOK_ADDNEWBOOK" // Mô tả về nội dung và tác giả
    static let OK = "OK_ADDNEWBOOK" // Đồng ý
    static let SUCCEEDED = "SUCCEEDED_ADDNEWBOOK" // Thành công
    static let MESSAGE_ADD_NEW_BOOK = "MESSAGE_ADDNEWBOOK" // Đã gửi thông tin sách
}

extension Gat.Text.BookSuggest {
    static let TITLE = "SUGGEST_BOOK"
    static let TOP_BORROWING_BOOK = "TOP_BORROWING_BOOK_SUGGEST"
    static let TOP_RATING = "TOP_RATTING_BOOK_SUGGEST"
    static let BOOK_NEARBY_YOU = "BOOK_NEARYBY_YOU_SUGGEST"
    static let YOU_MIGHT_LIKE = "YOU_MIGHT_LIKE_SUGGEST"
}

extension Gat.Text.Bookmark {
    static let BOOKMARK_TITLE = "BOOKMARK_TITLE"
    
    static let BOOK_BOOKMARK_TITLE = "BOOK_BOOKMARK_TITLE"
    
    static let REVIEW_BOOKMARK_TITLE = "REVIEW_BOOKMARK_TITLE"
    
    static let BOOK_DETAIL = "BOOK_DETAIL_BOOKMARK"
}

extension Gat.Text.BookUpdate {
    static let BOOK_UPDATE_TITLE = "BOOK_UPDATE_TITLE"
    
    static let WAITING_STATUS = "WAITING_STATUS_BOOKUPDATE"
    
    static let UPDATEDED_STATUS = "UPDATEDED_STATUS_BOOKUPDATE"
    
    static let CREATE_DATE_TITLE = "CREATE_DATE_TITLE_BOOKUPDATE"
}


extension Gat.Text.JoinBarcode {
    static let JOIN_MESSAGE = "JOIN_MESSAGE_JOINBARCODE" //Đã gửi yêu cầu tham gia bookstop. Quay lại màn hình trước.
}

extension Gat.Text.Gatup {
    static let BOOKSTOP_GATUP = "BOOKSTOP_GATUP" //Tủ sách GAT-UP
    static let INFORMATION_GATUP = "INFORMATION_GATUP" //Thông tin từ GAT-UP
    static let SCAN_GATUP = "SCAN_GATUP" //Quét QR code trên giá sách để bắt đầu \nQuét ngay >
    static let BOOKSTOP_ORGANIZATION_GATUP = "BOOKSTOP_ORGANIZATION_GATUP" //Tủ sách doanh nghiệp GAT-UP
    static let BOOKSTOP_ORGANIZATION_DESCRIPTION_GATUP = "BOOKSTOP_ORGANIZATION_DESCRIPTION_GATUP" //GAT-UP là một chương trình cung cấp tủ sách cho doanh nghiệp để xây dựng văn hóa doanh nghiệp
    static let LOOKING_INFORMATION_GATUP = "LOOKING_INFORMATION_GATUP" //Tìm hiểu ngay
    static let HIDE_GATUP = "HIDE_GATUP" //Ẩn tin
    static let ACECPT_GATUP = "ACECPT_GATUP" //Đã tham gia
    static let WAITING_GATUP = "WAITING_GATUP" //Chờ phê duyệt
    static let GATUP_TITLE = "GATUP_TITLE" //GAT-UP Offical
    
}

extension Gat.Text.Guideline {
    static let HELLO_MESSAGE = "HELLO_MESSAGE_GUILDELINE"
    static let PROFILE_PAGE = "PROFILE_PAGE_GUILDELINE"
    static let GO_TO_PROFILE_ALERT = "GO_TO_PROFILE_ALERT_GUILDELINE"
    static let TAP_PLUS_ADD_BOOK = "TAP_PLUS_ADD_BOOK_GUIDELINE"
    static let ADD_BOOK_TITLE = "ADD_BOOK_TITLE_GUIDELINE"
    static let ADD_TITLE = "ADD_TITLE_GUIDELINE"
    static let BORROW_TITLE = "BORROW_TITLE_GUIDELINE"
    static let SEARCH_BOOK = "SEARCH_BOOK_GUIDELINE"
    static let SEARCH_TITLE = "SEARCH_TITLE_GUIDELINE"
    static let ADD_BOOK_OR_BORROW_BOOK = "ADD_BOOK_OR_BORROW_BOOK_GUIDELINE"
    static let LENDING = "LENDING_GUIDELINE"
    static let COMPLETE = "COMPLETE_GUIDELINE"
}














































































